  
- name: Create Host Public IP 
  azure_rm_publicipaddress:
    resource_group: "{{ resource_Group_Name }}"
    name: lbPip
    allocation_method: static    



- name: create load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ resource_Group_Name }}"
    name: testloadbalancer1
    frontend_ip_configurations:
      - name: frontendipconf0
        public_ip_address: lbPip
    backend_address_pools:
      - name: backendaddrpool0
    probes:
      - name: prob0
        port: 22
    load_balancing_rules:
      - name: lbrbalancingrule0
        frontend_ip_configuration: frontendipconf0
        backend_address_pool: backendaddrpool0
        frontend_port: 500
        backend_port: 500
        probe: prob0
    load_balancing_rules:
      - name: lbrbalancingrule1
        frontend_ip_configuration: frontendipconf0
        backend_address_pool: backendaddrpool0
        frontend_port: 4500
        backend_port: 4500
        probe: prob0